import { Router, Request, Response } from 'express';
import bcrypt from 'bcryptjs';
import fs from 'fs/promises';
import path from 'path';
import { spawn } from 'child_process';
import db from '../db';
import { runFile } from '../utils/process-runner';

const router = Router();
db.exec(`CREATE TABLE IF NOT EXISTS webdav_accounts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL UNIQUE,
  home TEXT NOT NULL,
  domain TEXT NOT NULL DEFAULT '',
  enabled INTEGER NOT NULL DEFAULT 1,
  permissions TEXT NOT NULL DEFAULT 'rw',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
)`);

const WEBDAV_CONF_FILE = process.env.WEBDAV_CONF_FILE || '/etc/httpd/conf.d/hostpanel-webdav.conf';
const WEBDAV_PASSWD_FILE = process.env.WEBDAV_PASSWD_FILE || '/etc/httpd/.hostpanel-webdav-passwd';
const WEBDAV_ALLOWED_ROOT = process.env.WEBDAV_ALLOWED_ROOT || '/var/www/';
const validUser = (s: string) => /^[a-zA-Z0-9._-]{3,64}$/.test(s);
const validPath = (s: string) => typeof s === 'string' && s.startsWith(WEBDAV_ALLOWED_ROOT) && !s.includes('..') && !s.includes('\0');
const cleanDomain = (s: unknown) => typeof s === 'string' && /^[a-zA-Z0-9.-]{0,253}$/.test(s) ? s : '';

function config(row: any) {
  const writeGuard = row.permissions === 'ro' ? '\n  <LimitExcept GET OPTIONS PROPFIND>\n    Require all denied\n  </LimitExcept>' : '';
  return `Alias /webdav/${row.username} ${row.home}
<Directory ${row.home}>
  DAV On
  Options Indexes FollowSymLinks
  AllowOverride None
  AuthType Basic
  AuthName "HostPanel Web Disk"
  AuthBasicProvider file
  AuthUserFile ${WEBDAV_PASSWD_FILE}
  Require user ${row.username}${writeGuard}
</Directory>
`;
}

async function ensureParent(file: string) { await fs.mkdir(path.dirname(file), { recursive: true }); }
async function renderConfig() {
  const rows = db.prepare('SELECT * FROM webdav_accounts WHERE enabled=1 ORDER BY username').all() as any[];
  await ensureParent(WEBDAV_CONF_FILE);
  await fs.writeFile(WEBDAV_CONF_FILE, `# Generated by HostPanel. Do not edit by hand.\n\n${rows.map(config).join('\n')}`, { mode: 0o640 });
}

async function upsertPasswd(username: string, password: string) {
  await ensureParent(WEBDAV_PASSWD_FILE);
  try {
    await htpasswd(username, password);
    return;
  } catch {
    // Fallback for minimal test/container systems that lack htpasswd. Apache
    // httpd accepts bcrypt crypt hashes in htpasswd files on modern builds.
    const hash = await bcrypt.hash(password, 12);
    const existing = await fs.readFile(WEBDAV_PASSWD_FILE, 'utf8').catch(() => '');
    const lines = existing.split('\n').filter(Boolean).filter(l => !l.startsWith(`${username}:`));
    lines.push(`${username}:${hash}`);
    await fs.writeFile(WEBDAV_PASSWD_FILE, `${lines.join('\n')}\n`, { mode: 0o640 });
  }
}

function htpasswd(username: string, password: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const proc = spawn('htpasswd', ['-Bbi', WEBDAV_PASSWD_FILE, username, password], { stdio: ['ignore', 'ignore', 'pipe'] });
    let stderr = '';
    proc.stderr?.on('data', d => { stderr += d.toString(); });
    proc.on('error', reject);
    proc.on('close', code => code === 0 ? resolve() : reject(new Error(stderr || `htpasswd exited ${code}`)));
  });
}

async function removePasswdUser(username: string) {
  const existing = await fs.readFile(WEBDAV_PASSWD_FILE, 'utf8').catch(() => '');
  if (!existing) return;
  const lines = existing.split('\n').filter(Boolean).filter(l => !l.startsWith(`${username}:`));
  await fs.writeFile(WEBDAV_PASSWD_FILE, `${lines.join('\n')}${lines.length ? '\n' : ''}`, { mode: 0o640 });
}

async function reloadHttpd() {
  const result = await runFile('systemctl', ['reload', 'httpd']).catch((e: any) => ({ stdout: '', stderr: e.message || String(e) }));
  return { reloaded: !result.stderr, output: result.stdout || result.stderr };
}

router.get('/', (_req: Request, res: Response) => res.json(db.prepare('SELECT id, username, home, domain, enabled, permissions, created_at, updated_at FROM webdav_accounts ORDER BY username').all()));

router.post('/', async (req: Request, res: Response) => {
  const { username, home, enabled = 1, permissions = 'rw', password } = req.body || {};
  const domain = cleanDomain(req.body?.domain);
  if (!validUser(username)) return res.status(400).json({ error: 'Invalid username' });
  if (!validPath(home)) return res.status(400).json({ error: 'home must be under /var/www' });
  const existing: any = db.prepare('SELECT id FROM webdav_accounts WHERE username=?').get(username);
  if (!existing && (typeof password !== 'string' || password.length < 8)) return res.status(400).json({ error: 'password of at least 8 characters required for new WebDAV users' });
  if (password !== undefined && (typeof password !== 'string' || password.length < 8)) return res.status(400).json({ error: 'password must be at least 8 characters' });

  await fs.mkdir(home, { recursive: true, mode: 0o750 });
  db.prepare(`INSERT INTO webdav_accounts (username, home, domain, enabled, permissions, updated_at)
    VALUES (?, ?, ?, ?, ?, datetime('now'))
    ON CONFLICT(username) DO UPDATE SET home=excluded.home, domain=excluded.domain, enabled=excluded.enabled, permissions=excluded.permissions, updated_at=datetime('now')`)
    .run(username, home, domain, enabled ? 1 : 0, permissions === 'ro' ? 'ro' : 'rw');
  if (password) await upsertPasswd(username, password);
  await renderConfig();
  const reload = await reloadHttpd();
  res.json({ ...(db.prepare('SELECT id, username, home, domain, enabled, permissions, created_at, updated_at FROM webdav_accounts WHERE username=?').get(username) as any), reload });
});

router.delete('/:id', async (req: Request, res: Response) => {
  const row: any = db.prepare('SELECT * FROM webdav_accounts WHERE id=?').get(req.params.id);
  if (!row) return res.status(404).json({ error: 'WebDAV account not found' });
  db.prepare('DELETE FROM webdav_accounts WHERE id=?').run(req.params.id);
  await removePasswdUser(row.username);
  await renderConfig();
  const reload = await reloadHttpd();
  res.json({ success: true, reload });
});

router.get('/config-preview', (_req: Request, res: Response) => {
  const rows = db.prepare('SELECT * FROM webdav_accounts WHERE enabled=1 ORDER BY username').all() as any[];
  res.type('text/plain').send(rows.map(config).join('\n'));
});

router.post('/reload', async (_req: Request, res: Response) => {
  await renderConfig();
  res.json(await reloadHttpd());
});

export default router;
